### ISSUE TITLE
LUT usage and creating 'Enhanced Profiles'

### ISSUE THREAD

**Issue by ryancara** [abpy/FujifilmCameraProfiles#7]
Hey there,

How would one go about applying these sRGB LUTS? Creating a profile using Adobe Standard and loading one of the sRGB luts doesn't have the same result as manually creating the DCP file.  (Edit: are the SRGB LUTS also intended for images with Linear Contrast?)

Also, would there be any way of turning these DCP files into "Enhanced" Profiles that can be used on any camera model? 
It seems like Adobe changed the syntax of the Looktables and tone curves when they released the new 'enhanced profiles'. 

Cheers,

Ryan

**Comment by abpy** [comment]
The luts are intended to be used with a linear camera profile. An "Enhanced" profile can be made using the option/alt + 'new preset' dialog, set the Color Lookup Table to a cube file and set the color space to either displayp3 or srgb. Use a linear profile as the base profile. Use default settings including white balance 'as shot'.
If the profile is called 'Adobe Standard Linear' it will work for any camera with a profile with the same name.

It's more difficult to make a lut relative to adobe standard rather than linear and still get a good color match. (i may eventually try to make it work)
let me know if you have any other questions.

**Comment by ryancara** [comment]
Hey abpy,

Just made some profiles using the LUT's on Linear Profiles and am getting different results to the old DCP method. Is this normal behaviour or am I doing something wrong? 

Cheers,

Ryan

**Comment by ryancara** [comment]
Hey I've noticed when using a LUT on  a linear profile created using the DNG editor does not work as intended. As the <looktable> is still kept as Adobe standard. 

What is the process you've used to create these LUTs? Would love to have a crack at it myself. 

Cheers,

Ryan

**Comment by abpy** [comment]
In what way does it look different than intended?
It could be that a linear profile from dng profile editor will look slightly different because of the looktable and DefaultBlackRender.

The process involves exporting images from acr and I used python to process and output all the data and relied on scipy RBFInterpolator to interpolate the values.

**Comment by ryancara** [comment]
So following your instructions on creating a linear profile (deleting the looktable) works the same as using the DCP version. But when creating a Linear Profile with the DNG editor, it keeps the looktable as Adobe standard I believe. 

Anyway I think I’m all sorted now!
